version: '3'
services:
  pg:
    image: postgres
    container_name: rolls_api_db
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  roll_api:
    image: roll_api_v1
    build:
      context: .
    container_name: roll_api_v1
    depends_on:
      - pg
    command: ["/roll-app/scripts/run.sh"]
    ports:
      - 7777:8000

volumes:
  postgresdata: